### ISSUE TITLE
Create BMI Calculation

### ISSUE THREAD

**Issue by ANi13055** [ANi13055/BMI-Calculator#2]

**Comment by rpollock03** [comment]
Hi @ANi13055, I have submitted a pull request that fixes this issue and also adds a new feature. Hopefully you approve this but let me know if there are any problems. Thanks :)

**Comment by ANi13055** [comment]
@rpollock03 BMI calculation is giving wrong answer, try to fix it :)

**Comment by rpollock03** [comment]
> @rpollock03 BMI calculation is giving wrong answer, try to fix it :)

Ah, apologies. Should just be a case of changing the math (which I googled!), the function itself was working when I tested it!

**Comment by ANi13055** [comment]
@rpollock03 ohh, sorry I apologize. I put cm value instead of m
